---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2
        ports:
        - name: http
          containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: zipkin
spec:
  selector:
    app.kubernetes.io/name: zipkin
  ports:
  - name: http
    port: 9411
