{
 "title": "k8s_resource_usage_namespace",
 "tags": [
  "k8s",
  "resources",
  "view_namespace"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "_interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": "kube_pod_container_status_running"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster cpu usage for ns=\"$namespace\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$_interval])) by (cluster, namespace)",
     "legendFormat": "{{ cluster }} - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Cluster memory usage for ns=\"$namespace\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{ cluster }} - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage for ns=\"$namespace\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{namespace=~\"$namespace\"}) by (cluster, namespace)",
     "legendFormat": "{{ cluster }} - {{ namespace }}"
    }
   ]
  }
 ]
}