apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-grafana-datasource
  labels:
     grafana_datasource: "true"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-k8s:9090
      isDefault: true
      editable: false
